# color 参数说明（OpenCV HSV 标度：H∈[0,180]，S/V∈[0,255]）：
  # - hsv_red1: [Hmin, Smin, Vmin, Hmax, Smax, Vmax] 红色范围1（靠近 0°）
  # - hsv_red2: [Hmin, Smin, Vmin, Hmax, Smax, Vmax] 红色范围2（靠近 180°，红色跨 Hue 环需两段）
  # - hsv_blue: [Hmin, Smin, Vmin, Hmax, Smax, Vmax] 蓝色范围
  # - morph_kernel: 形态学核大小（像素，方形核边长，用于开/闭运算去噪与连通）
color:
  # HSV范围调整以减少反光干扰，提高饱和度阈值
  hsv_red1:  [0,   80,  80,  10, 255, 255]  # 提高S和V最小值以过滤反光
  hsv_red2:  [170, 80,  80, 180, 255, 255]  # 提高S和V最小值以过滤反光
  hsv_blue:  [100, 60,  60, 130, 255, 255]  # 提高S和V最小值以过滤反光
  morph_kernel: 2     # 适度形态学处理

gray:
  use_otsu: false
  thresh: 160  # 提高阈值减少反光噪声
  morph_k: 2   # 减小形态学核以保留细节

lightbar:
  min_area: 8          # 提高最小面积以过滤噪声
  min_ratio: 2.0       # 要求更细长的灯条
  max_ratio: 10.0      # 限制最大长宽比
  angle_upright_deg: 30.0  # 限制角度偏差
  post_morph: 2        # 后处理形态学操作

pair:
  height_diff_max: 0.25       # 更严格的高度相对差要求
  length_diff_max: 0.25       # 更严格的长度相对差要求
  tilt_diff_max_deg: 12.0     # 更严格的倾角差（度）
  slope_max: 0.20             # 更严格的中心连线斜率阈值
  gap_min_ratio: 0.8          # 中心距 / 平均高度 的最小值（更合理的间距）
  gap_max_ratio: 2.5          # 最大值（避免距离过远）

  # 打分权重（总和不必为1）- 增加几何约束权重
  w_height: 0.30
  w_length: 0.25
  w_tilt:   0.20
  w_slope:  0.15
  w_gap:    0.10

display:
  scale: 1.5
armor:
  width: 0.130     # 装甲板实际宽度(米) = 130 mm
  height: 0.050    # 装甲板实际高度(米) = 50 mm

pnp:
  reproj_thresh_px: 3.0   # 重投影误差阈值(像素)
  axis_len_m: 0.08        # 画坐标轴长度(米)
plate:
  top_offset_ratio: 0.08     # ↑↓边界相对灯条高度的偏移比例（按你的数据微调）
  bottom_offset_ratio: 0.06
