# ======== 相机内参与外参（给 Solver 用） ========

# 相机内参矩阵（按行写 3x3，一共 9 个数）
camera_matrix: [
  928.130989, 0.0,        377.572945,
  0.0,        930.138391, 283.892859,
  0.0,        0.0,        1.0
]

# 畸变系数 [k1, k2, p1, p2, k3]
distort_coeffs: [
  -0.254433647, 0.569431382, 0.00365405229, -0.00109433818, -1.33846840
]

# ========== 机体/云台/相机的外参 ==========
# 若你暂无精确外参，以下先用单位阵和零平移，流程可先跑通：
# R_gimbal2imubody：把“云台坐标系”转到“IMU 机身坐标系”的 3x3 旋转矩阵（Row-major）
R_gimbal2imubody: [
  1.0, 0.0, 0.0,
  0.0, 1.0, 0.0,
  0.0, 0.0, 1.0
]

# R_camera2gimbal：把“相机坐标系”转到“云台坐标系”的 3x3 旋转矩阵（Row-major）
R_camera2gimbal: [
  1.0, 0.0, 0.0,
  0.0, 1.0, 0.0,
  0.0, 0.0, 1.0
]

# t_camera2gimbal：相机原点在云台坐标系下的平移（米）
t_camera2gimbal: [ 0.0, 0.0, 0.0 ]
